name: build-maui-app
run-name: ${{githubactor}} is running a project build

#Trigger the run on a push to a non-main branch or manually

on:
  workflow_dispatch:
  push:
  # only run the debug build on non main branches
    branches-ignore: ["main"]
permissions: #Required for the test-reporter action
  contents: read
  actions: read
  checks: write

jobs:
  build-MAUI:
    runs-on: windows-latest
    defaults:
      run:
        # set the defualt shell to powershell
        shell: pwsh
    strategy:
      matrix:
        #dotnet-version: ['7.0.x','8.0.x']
        dotnet-version: ['7.0.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Instal MAUI workloads
        run: dotnet workload install maui
      - name: Build .NET MAUI application
        run: dotnet build src/

      - name: Test the build
        run: |
          dotnet test src/ --no-restore `
            --logger "trx;logfilename=test_results.trx" `
            --logger "trx;logfilename=test_results.html" 
      # Log the test results and publish them 
      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: success() || failure() #run this step even if previous step failed
        with:
          name: xUnit tests # the name of the check that will be created
          path: src/MAUITestProject/TestResults/*.trx
          reporter: dotnet-test
            
        
          
        
      
      
